[project]
title = "Citi Bike NYC Explorer APR 2025"
version = "0.1.0"
port = 8501
slug = "Citi Bike Dashboard"  
entrypoint = "hello.py"    

[branding]
name = "Citi Bike Dashboard"
logo = "images/citibike.jpeg"
favicon = "images/citibike.ico"
primaryColor = "#1E90FF"

[data.citibike_csv]
type = "csv"
path = "data/citibike-tripdata_ARP25.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"